/*Delete all data from all tables*/
DELETE FROM Report;
DELETE FROM Users;
DELETE FROM Songs;
DELETE FROM Albums;
DELETE FROM Artists;
DELETE FROM hasA;
DELETE FROM ListensTo;
/*Delete all tables*/
DROP TABLE IF EXISTS report CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS songs CASCADE;
DROP TABLE IF EXISTS albums CASCADE;
DROP TABLE IF EXISTS artists CASCADE;
DROP TABLE IF EXISTS hasa CASCADE;
DROP TABLE IF EXISTS listensto CASCADE;